namespace ADLXWrapper;

/// <include file='ADLX_MEMORYTIMING_DESCRIPTION.xml' path='doc/member[@name="ADLX_MEMORYTIMING_DESCRIPTION"]/*' />
public enum ADLX_MEMORYTIMING_DESCRIPTION
{
    /// <include file='ADLX_MEMORYTIMING_DESCRIPTION.xml' path='doc/member[@name="ADLX_MEMORYTIMING_DESCRIPTION.MEMORYTIMING_DEFAULT"]/*' />
    MEMORYTIMING_DEFAULT = 0,

    /// <include file='ADLX_MEMORYTIMING_DESCRIPTION.xml' path='doc/member[@name="ADLX_MEMORYTIMING_DESCRIPTION.MEMORYTIMING_FAST_TIMING"]/*' />
    MEMORYTIMING_FAST_TIMING,

    /// <include file='ADLX_MEMORYTIMING_DESCRIPTION.xml' path='doc/member[@name="ADLX_MEMORYTIMING_DESCRIPTION.MEMORYTIMING_FAST_TIMING_LEVEL_2"]/*' />
    MEMORYTIMING_FAST_TIMING_LEVEL_2,

    /// <include file='ADLX_MEMORYTIMING_DESCRIPTION.xml' path='doc/member[@name="ADLX_MEMORYTIMING_DESCRIPTION.MEMORYTIMING_AUTOMATIC"]/*' />
    MEMORYTIMING_AUTOMATIC,

    /// <include file='ADLX_MEMORYTIMING_DESCRIPTION.xml' path='doc/member[@name="ADLX_MEMORYTIMING_DESCRIPTION.MEMORYTIMING_MEMORYTIMING_LEVEL_1"]/*' />
    MEMORYTIMING_MEMORYTIMING_LEVEL_1,

    /// <include file='ADLX_MEMORYTIMING_DESCRIPTION.xml' path='doc/member[@name="ADLX_MEMORYTIMING_DESCRIPTION.MEMORYTIMING_MEMORYTIMING_LEVEL_2"]/*' />
    MEMORYTIMING_MEMORYTIMING_LEVEL_2,
}
