namespace ADLXWrapper;

/// <include file='ADLX_DISPLAY_CONNECTOR_TYPE.xml' path='doc/member[@name="ADLX_DISPLAY_CONNECTOR_TYPE"]/*' />
public enum ADLX_DISPLAY_CONNECTOR_TYPE
{
    /// <include file='ADLX_DISPLAY_CONNECTOR_TYPE.xml' path='doc/member[@name="ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_UNKNOWN"]/*' />
    DISPLAY_CONTYPE_UNKNOWN = 0,

    /// <include file='ADLX_DISPLAY_CONNECTOR_TYPE.xml' path='doc/member[@name="ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_VGA"]/*' />
    DISPLAY_CONTYPE_VGA,

    /// <include file='ADLX_DISPLAY_CONNECTOR_TYPE.xml' path='doc/member[@name="ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_DVI_D"]/*' />
    DISPLAY_CONTYPE_DVI_D,

    /// <include file='ADLX_DISPLAY_CONNECTOR_TYPE.xml' path='doc/member[@name="ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_DVI_I"]/*' />
    DISPLAY_CONTYPE_DVI_I,

    /// <include file='ADLX_DISPLAY_CONNECTOR_TYPE.xml' path='doc/member[@name="ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_CVDONGLE_NTSC"]/*' />
    DISPLAY_CONTYPE_CVDONGLE_NTSC,

    /// <include file='ADLX_DISPLAY_CONNECTOR_TYPE.xml' path='doc/member[@name="ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_CVDONGLE_JPN"]/*' />
    DISPLAY_CONTYPE_CVDONGLE_JPN,

    /// <include file='ADLX_DISPLAY_CONNECTOR_TYPE.xml' path='doc/member[@name="ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_CVDONGLE_NONI2C_JPN"]/*' />
    DISPLAY_CONTYPE_CVDONGLE_NONI2C_JPN,

    /// <include file='ADLX_DISPLAY_CONNECTOR_TYPE.xml' path='doc/member[@name="ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_CVDONGLE_NONI2C_NTSC"]/*' />
    DISPLAY_CONTYPE_CVDONGLE_NONI2C_NTSC,

    /// <include file='ADLX_DISPLAY_CONNECTOR_TYPE.xml' path='doc/member[@name="ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_PROPRIETARY"]/*' />
    DISPLAY_CONTYPE_PROPRIETARY,

    /// <include file='ADLX_DISPLAY_CONNECTOR_TYPE.xml' path='doc/member[@name="ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_HDMI_TYPE_A"]/*' />
    DISPLAY_CONTYPE_HDMI_TYPE_A,

    /// <include file='ADLX_DISPLAY_CONNECTOR_TYPE.xml' path='doc/member[@name="ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_HDMI_TYPE_B"]/*' />
    DISPLAY_CONTYPE_HDMI_TYPE_B,

    /// <include file='ADLX_DISPLAY_CONNECTOR_TYPE.xml' path='doc/member[@name="ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_SVIDEO"]/*' />
    DISPLAY_CONTYPE_SVIDEO,

    /// <include file='ADLX_DISPLAY_CONNECTOR_TYPE.xml' path='doc/member[@name="ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_COMPOSITE"]/*' />
    DISPLAY_CONTYPE_COMPOSITE,

    /// <include file='ADLX_DISPLAY_CONNECTOR_TYPE.xml' path='doc/member[@name="ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_RCA_3COMPONENT"]/*' />
    DISPLAY_CONTYPE_RCA_3COMPONENT,

    /// <include file='ADLX_DISPLAY_CONNECTOR_TYPE.xml' path='doc/member[@name="ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_DISPLAYPORT"]/*' />
    DISPLAY_CONTYPE_DISPLAYPORT,

    /// <include file='ADLX_DISPLAY_CONNECTOR_TYPE.xml' path='doc/member[@name="ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_EDP"]/*' />
    DISPLAY_CONTYPE_EDP,

    /// <include file='ADLX_DISPLAY_CONNECTOR_TYPE.xml' path='doc/member[@name="ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_WIRELESSDISPLAY"]/*' />
    DISPLAY_CONTYPE_WIRELESSDISPLAY,

    /// <include file='ADLX_DISPLAY_CONNECTOR_TYPE.xml' path='doc/member[@name="ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_USB_TYPE_C"]/*' />
    DISPLAY_CONTYPE_USB_TYPE_C,
}
