namespace ADLXWrapper;

/// <include file='ADLX_SMARTSHIFT_ECO_INACTIVE_REASON.xml' path='doc/member[@name="ADLX_SMARTSHIFT_ECO_INACTIVE_REASON"]/*' />
public enum ADLX_SMARTSHIFT_ECO_INACTIVE_REASON
{
    /// <include file='ADLX_SMARTSHIFT_ECO_INACTIVE_REASON.xml' path='doc/member[@name="ADLX_SMARTSHIFT_ECO_INACTIVE_REASON.INACTIVE_REASON_UNKNOWN"]/*' />
    INACTIVE_REASON_UNKNOWN = 0,

    /// <include file='ADLX_SMARTSHIFT_ECO_INACTIVE_REASON.xml' path='doc/member[@name="ADLX_SMARTSHIFT_ECO_INACTIVE_REASON.INACTIVE_REASON_PRIMARY_DISPLAY_CONNECTED_TO_DGPU"]/*' />
    INACTIVE_REASON_PRIMARY_DISPLAY_CONNECTED_TO_DGPU,

    /// <include file='ADLX_SMARTSHIFT_ECO_INACTIVE_REASON.xml' path='doc/member[@name="ADLX_SMARTSHIFT_ECO_INACTIVE_REASON.INACTIVE_REASON_DETACHABLE_GPU_CONNECTED"]/*' />
    INACTIVE_REASON_DETACHABLE_GPU_CONNECTED,

    /// <include file='ADLX_SMARTSHIFT_ECO_INACTIVE_REASON.xml' path='doc/member[@name="ADLX_SMARTSHIFT_ECO_INACTIVE_REASON.INACTIVE_REASON_SESSION_INACTIVE"]/*' />
    INACTIVE_REASON_SESSION_INACTIVE,

    /// <include file='ADLX_SMARTSHIFT_ECO_INACTIVE_REASON.xml' path='doc/member[@name="ADLX_SMARTSHIFT_ECO_INACTIVE_REASON.INACTIVE_REASON_MULTIPLE_SESSION_ACTIVE"]/*' />
    INACTIVE_REASON_MULTIPLE_SESSION_ACTIVE,
}
