namespace ADLXWrapper;

/// <include file='ADLX_VARIABLE_GRAPHICS_MEMORY_MODE.xml' path='doc/member[@name="ADLX_VARIABLE_GRAPHICS_MEMORY_MODE"]/*' />
public enum ADLX_VARIABLE_GRAPHICS_MEMORY_MODE
{
    /// <include file='ADLX_VARIABLE_GRAPHICS_MEMORY_MODE.xml' path='doc/member[@name="ADLX_VARIABLE_GRAPHICS_MEMORY_MODE.VARIABLE_GRAPHICS_MEMORY_MODE_AUTO"]/*' />
    VARIABLE_GRAPHICS_MEMORY_MODE_AUTO = 0,

    /// <include file='ADLX_VARIABLE_GRAPHICS_MEMORY_MODE.xml' path='doc/member[@name="ADLX_VARIABLE_GRAPHICS_MEMORY_MODE.VARIABLE_GRAPHICS_MEMORY_MODE_CUSTOM"]/*' />
    VARIABLE_GRAPHICS_MEMORY_MODE_CUSTOM = 1,
}
