namespace ADLXWrapper;

/// <include file='ADLX_WAIT_FOR_VERTICAL_REFRESH_MODE.xml' path='doc/member[@name="ADLX_WAIT_FOR_VERTICAL_REFRESH_MODE"]/*' />
public enum ADLX_WAIT_FOR_VERTICAL_REFRESH_MODE
{
    /// <include file='ADLX_WAIT_FOR_VERTICAL_REFRESH_MODE.xml' path='doc/member[@name="ADLX_WAIT_FOR_VERTICAL_REFRESH_MODE.WFVR_ALWAYS_OFF"]/*' />
    WFVR_ALWAYS_OFF = 0,

    /// <include file='ADLX_WAIT_FOR_VERTICAL_REFRESH_MODE.xml' path='doc/member[@name="ADLX_WAIT_FOR_VERTICAL_REFRESH_MODE.WFVR_OFF_UNLESS_APP_SPECIFIES"]/*' />
    WFVR_OFF_UNLESS_APP_SPECIFIES,

    /// <include file='ADLX_WAIT_FOR_VERTICAL_REFRESH_MODE.xml' path='doc/member[@name="ADLX_WAIT_FOR_VERTICAL_REFRESH_MODE.WFVR_ON_UNLESS_APP_SPECIFIES"]/*' />
    WFVR_ON_UNLESS_APP_SPECIFIES,

    /// <include file='ADLX_WAIT_FOR_VERTICAL_REFRESH_MODE.xml' path='doc/member[@name="ADLX_WAIT_FOR_VERTICAL_REFRESH_MODE.WFVR_ALWAYS_ON"]/*' />
    WFVR_ALWAYS_ON,
}
