namespace ADLXWrapper;

/// <include file='ADLX_AFMF_PERFORMANCE_MODE_TYPE.xml' path='doc/member[@name="ADLX_AFMF_PERFORMANCE_MODE_TYPE"]/*' />
public enum ADLX_AFMF_PERFORMANCE_MODE_TYPE
{
    /// <include file='ADLX_AFMF_PERFORMANCE_MODE_TYPE.xml' path='doc/member[@name="ADLX_AFMF_PERFORMANCE_MODE_TYPE.AFMF_PERFORMANCE_MODE_AUTO"]/*' />
    AFMF_PERFORMANCE_MODE_AUTO = 0,

    /// <include file='ADLX_AFMF_PERFORMANCE_MODE_TYPE.xml' path='doc/member[@name="ADLX_AFMF_PERFORMANCE_MODE_TYPE.AFMF_PERFORMANCE_MODE_QUALITY"]/*' />
    AFMF_PERFORMANCE_MODE_QUALITY,

    /// <include file='ADLX_AFMF_PERFORMANCE_MODE_TYPE.xml' path='doc/member[@name="ADLX_AFMF_PERFORMANCE_MODE_TYPE.AFMF_PERFORMANCE_MODE_PERFORMANCE"]/*' />
    AFMF_PERFORMANCE_MODE_PERFORMANCE,
}
