// BuildADLX.h
#pragma once
//#include "../ADLX/SDK/Include/<Windows.h>          // if the SDK headers need it

// Since we pass the include path in the config, we can just list filenames.
// ClangSharp will merge all these into one "Context", preventing duplicates.

#include "../ADLX/SDK/Include/ADLX.h"
#include "../ADLX/SDK/Include/ADLXDefines.h"
#include "../ADLX/SDK/Include/ADLXStructures.h"
#include "../ADLX/SDK/Include/ADLXVersion.h"
#include "../ADLX/SDK/Include/I3DSettings.h"
#include "../ADLX/SDK/Include/I3DSettings1.h"
#include "../ADLX/SDK/Include/I3DSettings2.h"
#include "../ADLX/SDK/Include/IApplications.h"
#include "../ADLX/SDK/Include/IChangedEvent.h"
#include "../ADLX/SDK/Include/ICollections.h"
#include "../ADLX/SDK/Include/IDesktops.h"
#include "../ADLX/SDK/Include/IDisplay3DLUT.h"
#include "../ADLX/SDK/Include/IDisplayGamma.h"
#include "../ADLX/SDK/Include/IDisplayGamut.h"
#include "../ADLX/SDK/Include/IDisplays.h"
#include "../ADLX/SDK/Include/IDisplays1.h"
#include "../ADLX/SDK/Include/IDisplays2.h"
#include "../ADLX/SDK/Include/IDisplays3.h"
#include "../ADLX/SDK/Include/IDisplaySettings.h"
#include "../ADLX/SDK/Include/IGPUAutoTuning.h"
#include "../ADLX/SDK/Include/IGPUManualFanTuning.h"
#include "../ADLX/SDK/Include/IGPUManualGFXTuning.h"
#include "../ADLX/SDK/Include/IGPUManualPowerTuning.h"
#include "../ADLX/SDK/Include/IGPUManualVRAMTuning.h"
#include "../ADLX/SDK/Include/IGPUPresetTuning.h"
#include "../ADLX/SDK/Include/IGPUTuning.h"
#include "../ADLX/SDK/Include/IGPUTuning1.h"
#include "../ADLX/SDK/Include/II2C.h"
#include "../ADLX/SDK/Include/ILog.h"
#include "../ADLX/SDK/Include/IMultiMedia.h"
#include "../ADLX/SDK/Include/IPerformanceMonitoring.h"
#include "../ADLX/SDK/Include/IPerformanceMonitoring1.h"
#include "../ADLX/SDK/Include/IPerformanceMonitoring2.h"
#include "../ADLX/SDK/Include/IPerformanceMonitoring3.h"
#include "../ADLX/SDK/Include/IPowerTuning.h"
#include "../ADLX/SDK/Include/IPowerTuning1.h"
#include "../ADLX/SDK/Include/ISmartAccessMemory.h"
#include "../ADLX/SDK/Include/ISystem.h"
#include "../ADLX/SDK/Include/ISystem1.h"
#include "../ADLX/SDK/Include/ISystem2.h"
